version: "3.9"
services:
  sitsmart:
    build: .
    image: sitsmart:latest
    container_name: sitsmart
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - FEATURE_BUFFER_SECONDS=${FEATURE_BUFFER_SECONDS:-3}
      - NOTIFICATION_WEBHOOK_URL=${NOTIFICATION_WEBHOOK_URL:-http://127.0.0.1:8000/api/notifications/webhook}
      - RL_AGENT_STATE_PATH=${RL_AGENT_STATE_PATH:-/app/train/rl_agent_state.json}
    restart: unless-stopped
